default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Core Home Assistant settings & entity customizations
homeassistant:
  # Load per-entity customizations (friendly_name, icon, etc.)
  customize: !include customize.yaml

recorder:
  purge_keep_days: 7
