default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  db_url: mysql://ha:__DB_PASSWORD__@mariadb:3306/homeassistant?charset=utf8mb4
  purge_keep_days: 7
